[book]
title = "starpkg user guide"
author = "Alex Bates"
description = "A tool for creating composable Paper Mario mods."
language = "en"
src = "docs"

[output.html]
curly-quotes = true
no-section-label = false
git-repository-url = "https://github.com/nanaian/starpkg"
