style: github
template: CHANGELOG.tpl.md
info:
  repository_url: https://github.com/nanaian/starpkg
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - improve
  commit_groups:
    title_maps:
      feat: Features
      improve: Improvements
      fix: Fixes
      perf: Performance
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
