# TODO: docs versioning
# i.e. https://imalex.xyz/starpkg/latest -> docs built from latest release
#      https://imalex.xyz/starpkg/vX.Y.Z -> docs built from release X.Y.Z

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

name: Docs

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.3.5'

      - name: Build
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./book
